version: '3.8'

services:
    # Development service
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: vue-app-dev
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev -- --host

    # Production service
    prod:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vue-app-prod
        ports:
            - '8080:80'
        environment:
            - NODE_ENV=production
